name: Deploy Database

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy DACPAC
      run: |
        az sql server dacpac deploy \
          --source ExamsDB.dacpac \
          --server ${{ secrets.SQL_SERVER_NAME }} \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
          --database-name ExamsDB \
          --edition Standard \
          --edition Standard
